### PR TITLE
Added compatibility with the 3B+, 3A+, and Zero W

### PR DESCRIPTION
**Pull request by sarcasticnature**
The Raspberry Pi 3B+, 3A+, and Zero W contain the same bluetooth module
as the original Raspberry Pi 3, which means they use the same serial port
configuration. The Sleepy-Pi-Setup.sh script did not account for this
and would incorrectly set up the serial port used to program the Sleepy Pi 2.

The Sleepy-Pi-Setup.sh script was modified to configure
the ttyS0 serial port on these boards, instead of the ttyAMA0 serial
port.

### CODE REVIEW

**Comment by nzbaxterman** [comment]
Please also add Raspberry Pi Zero (non W) support. Board type is 900093:

elif [ "$RpiCPU" == "900093" ]; then
    echo "RapberryPi Zero detected"
    RPi3=true

**Comment by sarcasticnature** [comment]
Does the non W Pi Zero have the same serial port setup?  My understanding is that it only applies to the Pi 3's and Zero W, which use their 'primary' UART (PL001) for a Bluetooth module by default.

**Comment by nzbaxterman** [comment]
I presume so. After I made this code change last night, to detect board type 900093, I was able to upload the blink sketch. I get a couple of Broken Pipe messages, which apparently is inconsequential, but everything else is fine.

Happy to run commands or do more testing if you need it.

Thanks
Simon

**Comment by sarcasticnature** [comment]
Did the script not work without modifications?  If so, which (or all) of "serial0", "serial1", "ttyS0", and "ttyAMA0" show up in /dev?

Thanks in advance, I don't have a non-W Pi Zero on hand.

**Comment by nzbaxterman** [comment]
Yes, once I updated the script it worked fine.

Here are the devices:
crw-rw---- 1 root dialout 204, 64 Jan 27 17:30 /dev/ttyAMA0
lrwxrwxrwx 1 root root 7 Jan 27 17:28 /dev/ttyS0 -> ttyAMA0

-Simon

**Pull request merged**
